// <auto-generated />
namespace jamescms.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Indexes : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Indexes));
        
        string IMigrationMetadata.Id
        {
            get { return "201302091047559_Indexes"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
