// <auto-generated />
namespace jamescms.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Original : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Original));
        
        string IMigrationMetadata.Id
        {
            get { return "201302062111428_Original"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
