// <auto-generated />
namespace jamescms.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class CodeSnippit : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CodeSnippit));
        
        string IMigrationMetadata.Id
        {
            get { return "201302100216376_CodeSnippit"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
