// <auto-generated />
namespace jamescms.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class CodeSnippit1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CodeSnippit1));
        
        string IMigrationMetadata.Id
        {
            get { return "201302100217380_CodeSnippit1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
