// <auto-generated />
namespace jamescms.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Setting : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Setting));
        
        string IMigrationMetadata.Id
        {
            get { return "201303011347573_Setting"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
